# Generated by Django 5.2.8 on 2025-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mediacontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video')], default='video', max_length=10),
        ),
    ]
